// Mock data only - the Discover page makes no API calls.
export const profiles = [
  {
    id: 'p1',
    name: 'Riya',
    age: 24,
    profession: 'Designer',
    location: 'Bangalore',
    photoUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=900&q=80',
    verified: true,
    isNew: true,
    online: true,
    vibeMatch: 92,
    prompts: [
      { title: "I'll die on this hill", answer: 'Pineapple pizza is actually good 🍕' },
      { title: 'My perfect Sunday', answer: 'Coffee, a good book and no plans ☕' },
    ],
    interests: [
      { icon: '🎧', label: 'Indie' },
      { icon: '✈️', label: 'Travel' },
      { icon: '📷', label: 'Photography' },
    ],
    extraInterests: 2,
  },
  {
    id: 'p2',
    name: 'Arjun',
    age: 26,
    profession: 'Product Designer',
    location: 'Bangalore',
    photoUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=900&q=80',
    verified: true,
    isNew: false,
    online: false,
    vibeMatch: 89,
    prompts: [
      { title: 'Ask me about', answer: 'My dog Bruno 🐶' },
      { title: 'Green flag I look for', answer: 'Replies with voice notes 🎙️' },
    ],
    interests: [
      { icon: '🎸', label: 'Rock' },
      { icon: '🏔️', label: 'Treks' },
      { icon: '☕', label: 'Coffee' },
    ],
    extraInterests: 3,
  },
  {
    id: 'p3',
    name: 'Meera',
    age: 25,
    profession: 'Illustrator',
    location: 'Mumbai',
    photoUrl: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=900&q=80',
    verified: false,
    isNew: true,
    online: true,
    vibeMatch: 87,
    prompts: [
      { title: 'A random fact I love', answer: 'Octopuses have three hearts 🐙' },
      { title: 'Best travel story', answer: 'Missed a flight, found a festival 🎪' },
    ],
    interests: [
      { icon: '🎨', label: 'Art' },
      { icon: '🍜', label: 'Ramen' },
      { icon: '📚', label: 'Fiction' },
    ],
    extraInterests: 1,
  },
  {
    id: 'p4',
    name: 'Kabir',
    age: 27,
    profession: 'Backend Engineer',
    location: 'Delhi',
    photoUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=900&q=80',
    verified: true,
    isNew: false,
    online: false,
    vibeMatch: 84,
    prompts: [
      { title: 'My simple pleasures', answer: 'Chai + rain + lo-fi playlists 🌧️' },
      { title: "I'm weirdly good at", answer: 'Guessing movie plots in 10 min 🎬' },
    ],
    interests: [
      { icon: '🏏', label: 'Cricket' },
      { icon: '🎮', label: 'Gaming' },
      { icon: '🍳', label: 'Cooking' },
    ],
    extraInterests: 2,
  },
  {
    id: 'p5',
    name: 'Ananya',
    age: 23,
    profession: 'Filmmaker',
    location: 'Goa',
    photoUrl: 'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?auto=format&fit=crop&w=900&q=80',
    verified: true,
    isNew: true,
    online: true,
    vibeMatch: 81,
    prompts: [
      { title: 'Two truths and a lie', answer: "I've surfed at sunrise. Twice. 🌊" },
      { title: 'My love language', answer: 'Sharing playlists, obviously 🎵' },
    ],
    interests: [
      { icon: '🎬', label: 'Cinema' },
      { icon: '🏄', label: 'Surfing' },
      { icon: '🌱', label: 'Vegan' },
    ],
    extraInterests: 4,
  },
]
